CREATE TABLE BANK (
  TYPE VARCHAR(20) NOT NULL ,
  VALUE INTEGER NOT NULL ,
  AMOUNT INTEGER,
  PRIMARY KEY (TYPE)
);

CREATE TABLE USER (
    ACCOUNTNUMBER INTEGER NOT NULL,
    PIN VARCHAR(64) NOT NULL,
    OPENINGBALANCE INT,
    OVERDRAFT INT,
    PRIMARY KEY (ACCOUNTNUMBER)
);